version: '3.8'

services:
  db:
    image: postgres:15
    container_name: evcharge_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: evcharge
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
